apiVersion: v2
name: minio
description: Minio object storage for Control Plane

type: application
version: 1.1.0
appVersion: "RELEASE.2025-09-07T16-13-09Z"

annotations:
  created: "2025-11-19"
  lastModified: "2025-11-26"
  category: "storage"
  createsGvc: false