apiVersion: v2
name: cpln-task-runner
description: A self-hosted task queue and scheduler service similar to Google Cloud Tasks
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: redis
    version: 3.0.2
    repository: "https://controlplane-com.github.io/helm-packages"

annotations:
  created: "2025-12-03"
  lastModified: "2025-12-05"
  category: "queue"
  createsGvc: false